### PR TITLE
Add ability to configure durableDelete property for Batch Client Policies

### PR DESCRIPTION
**Pull request by RomanCht**
The same durableDelete property configuration as for WritePolicy:
https://github.com/aerospike-community/spring-data-aerospike-starters/blob/main/spring-boot-autoconfigure-data-aerospike/src/main/java/org/springframework/boot/autoconfigure/aerospike/AerospikeProperties.java#L205-L212

### CODE REVIEW

**Comment by amizurov** [comment]
@agrgr, @roimenashe, @reugn Hey guys, PTAL. It would be great if we could patch previous versions аs well. Thanks.

**Comment by reugn** [comment]
@RomanCht, @amizurov, thanks for the PR. We're looking into it.

**Comment by RomanCht** [comment]
@agrgr, @roimenashe, @reugn Guys, sorry for being pushy, have you had a chance to check this out?

**Comment by RomanCht** [comment]
Guys, thank you for merge!

We would like to have other minor versions to be patched with this change.
But this repository doesn't have separate branches for these versions _(0.14.x, 0.13.x ... 0.8.x)_ so there's no where to make Pull requests to.

Could you please create those branches or is there any other way to patch these minor versions somehow?

**Comment by reugn** [comment]
@RomanCht what is your motivation to patch older versions instead of updating to the new one in all services? We plan to coordinate the release with you to make sure that it meets your needs.

**Comment by RomanCht** [comment]
@reugn hi,
we plan to switch on durable delete for a big number of services, which are using different combinations of aerospike client, spring and other internal dependencies. It'll be much easier to just increment needed patch version of the starter without the risk to break something or cause additional code migration complexity

**Pull request merged**
