### PR TITLE
Add minn connection per node property

### PR DESCRIPTION
**Pull request by mrozk**

### CODE REVIEW

**Comment by mrozk** [comment]
Is it possible to create a patch for version 0.7.1, because we haven't upgrade aerospike version yet, it would be great to have this config for older version of aerospike client

**Comment by mrozk** [comment]
/**
	 * Minimum number of synchronous connections allowed per server node.  Preallocate min connections
	 * on client node creation.  The client will periodically allocate new connections if count falls
	 * below min connections.
	 * <p>
	 * Server proto-fd-idle-ms and client {@link ClientPolicy#maxSocketIdle} should be set to zero
	 * (no reap) if minConnsPerNode is greater than zero.  Reaping connections can defeat the purpose
	 * of keeping connections in reserve for a future burst of activity.
	 * <p>
	 * Default: 0
	 */
	public int minConnsPerNode;

**Review by ijusti — APPROVED** [review]

**Comment by ijusti** [comment]
@roimenashe can you please merge it

**Comment by roimenashe** [comment]
@mrozk @ijusti 
Released 2 new versions:
0.8.1 (latest) https://github.com/aerospike-community/spring-data-aerospike-starters/releases/tag/0.8.1
0.7.2 https://github.com/aerospike-community/spring-data-aerospike-starters/releases/tag/0.7.2

Both contain this change.
It might take up to 24 hours to sync in Maven Central.

**Comment by mrozk** [comment]
Thank you so much guys!

**Pull request merged**
